import starlight from '@astrojs/starlight';
// import starlightDocSearch from '@astrojs/starlight-docsearch';
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from 'astro/config';
import { unified } from '@astrojs/markdown-remark';
import starlightBlog from 'starlight-blog';
import starlightChangelogs, { makeChangelogsSidebarLinks } from 'starlight-changelogs';
import starlightOpenAPI, { createOpenAPISidebarGroup } from 'starlight-openapi'
import { buildRedirects } from './scripts/build-redirects.mjs';

// Single "API" sidebar parent. Each audience below is one OpenAPI schema, so the
// rendered tree is Audience › Resource(tag) › Operation — three levels, no per-group
// or audience-wrapper nesting. Snapshots live in ./schemas/<audience>.json and are
// refreshed by `npm run schemas:sync` from monorepo-java's BUILD OUTPUT -- no deployment
// is involved, so a snapshot cannot carry the wrong environment. Audience ids match the
// upstream springdoc group ids one-for-one; sync-schemas.ts is the authoritative map of
// which generator produces which.
const apiSidebarGroup = createOpenAPISidebarGroup()

// The Partner reference moved from /integrations-api/partner/ to /partner-api/partner/ when it
// got its own base path (see AUDIENCES). Those pages are generated by starlight-openapi, not
// content files, so buildRedirects() — which works off migration-mapping.json's docs paths —
// cannot see them. They are declared here instead, per locale.
//
// INDEX PAGES ONLY, and deliberately so. Astro rejects a `[...slug]` redirect whose destination
// is not itself a declared route (InvalidRedirectDestination), and starlight-openapi emits
// concrete static pages rather than a spread route — so a catch-all is not expressible. It would
// not have helped anyway: the operation slugs changed with the service rename (SearchDestinations
// -> Search), so old deep links have no 1:1 successor. They land on the reference index instead.
//
// The same block also catches /integrations-api/integrator/, the prefix used before the audience
// was renamed to `partner`; 44 content links still pointed there and are now re-pointed, but
// external links and bookmarks are not.
const API_LOCALES = ["ar", "bg", "ca", "cs", "da", "de", "el", "es", "es-AR", "es-MX", "et", "fi", "fr", "he", "hi", "hr", "hu", "id", "is", "it", "ja", "ko", "lt", "lv", "ms", "nl", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sl", "sr", "sv", "th", "tl", "tr", "uk", "vi", "zh-CN", "zh-TW"]
const partnerApiRedirects = Object.fromEntries(
  ['', ...API_LOCALES.map((l) => `/${l}`)].flatMap((prefix) => [
    [`${prefix}/integrations-api/partner`, `${prefix}/partner-api/partner`],
    [`${prefix}/integrations-api/integrator`, `${prefix}/partner-api/partner`],
  ]),
)


// audience id -> [sidebar label, base path prefix]. Three source apps:
//   inventory-app     — every audience with the 'api' prefix below
//   integrations-app  — 'channel-manager' (the vendor / channel-manager API)
//   partner-app       — 'partner' (the Partner Integrator API, documented as gRPC)
// The prefix is a docs URL segment, not the fetch source. Partner has its own 'partner-api'
// prefix rather than sharing 'integrations-api': it is a separate product on a separate host,
// and filing it under "integrations" implied it was part of the channel-manager surface.
const AUDIENCES = [
  ['reference', 'Reference', 'api'],
  ['extranet', 'Extranet', 'api'],
  ['booking-engine', 'Booking Engine', 'api'],
  ['studio', 'Studio', 'api'],
  ['social', 'Social', 'api'],
  ['link-manager', 'Link Manager', 'api'],
  ['settings', 'Settings', 'api'],
  ['payment', 'Payment', 'api'],
  ['user', 'User', 'api'],
  ['travel-agent', 'Travel Agent', 'api'],
  // Webhook management endpoints + the OpenAPI 3.1 `webhooks:` object (one page per event Wink POSTs
  // to subscribers, rendered by starlight-openapi as a "Webhooks" group) + `x-wink-event-types`.
  ['webhooks', 'Webhooks', 'api'],
  ['partner', 'Partner', 'partner-api'],
  ['channel-manager', 'Integrator', 'integrations-api'],
]

const openApiSnippets = {
  operation: {
    clients: { javascript: ['fetch'], shell: ['curl'] },
    default: { target: 'shell', client: 'curl' },
  },
}

// Build a starlight-openapi schema entry for one audience.
const toApiSchema = ([audience, label, apiBase]) => ({
  base: `${apiBase}/${audience}`,
  schema: `./schemas/${audience}.json`,
  sidebar: {
    label,
    collapsed: true,
    group: apiSidebarGroup,
    // Sort the resource sections within each audience alphabetically (the schema
    // "Overview" link is rendered before the tags, so it stays first).
    tags: { sort: 'alphabetical' },
    operations: { badges: true, labels: 'summary', sort: 'alphabetical' },
  },
  snippets: openApiSnippets,
})

import icon from 'astro-icon';

import markdoc from '@astrojs/markdoc';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://wink.travel',
  redirects: { ...buildRedirects(), '/home-v2': '/', ...partnerApiRedirects },
  // Astro v7 defaults Markdown rendering to the native `satteri` processor, which does
  // not run remark/rehype plugins. Starlight registers its transforms for whichever
  // processor is configured, but `starlight-blog` still injects its excerpt remark plugin
  // via the deprecated `markdown.remarkPlugins` option. Opt back into the unified
  // (remark/rehype) pipeline so those plugins keep running, preserving v6 behavior.
  markdown: {
    processor: unified(),
  },
  image: {
    domains: ['res.cloudinary.com']
  },
  integrations: [starlight({
    head: [
      // og:image is set per-page in custom-head.astro (generated OG cards for
      // marketing pages, global card fallback otherwise).
      {
        tag: 'script',
        attrs: {
          src: 'https://www.googletagmanager.com/gtag/js?id=G-688LY2TNNR',
          async: true,
        },
      },
      {
        tag: 'script',
        content: `
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-688LY2TNNR');`
      },
    ],
    favicon: 'favicon.ico',
    logo: {
      src: './src/assets/logo.png',
      replacesTitle: true
    },
    title: 'Wink',
    description: 'A travel booking platform for those in the know.',
    customCss: [
      // Path to your Tailwind global CSS — must be first!
      './src/styles/starwind.css',
      './src/styles/tweaks.css',
    ],
    defaultLocale: 'root',
    lastUpdated: false,
    titleDelimiter: '|',
    // editLink: {
    //   baseUrl: 'https://github.com/wink-travel/docs/edit/master/',
    // },
    plugins: [
      // Generate the OpenAPI reference pages from local snapshots in ./schemas/.
      // Refresh snapshots with `npm run schemas:sync`.
      // Sort audience sections alphabetically by label (Account, Affiliate, Consumer,
      // Partner, Platform, Supplier). The "Overview" link is a separate sidebar item, so
      // it stays first.
      starlightOpenAPI([...AUDIENCES].sort((a, b) => a[1].localeCompare(b[1])).map(toApiSchema)),
      starlightBlog({
        title: "Wink updates",
        navigation: 'none',
        authors: {
          may: {
            name: 'May Rawddon',
            title: 'Marketing & Media',
            url: 'https://i.trvl.as/starringmay',
            picture: '/src/assets/may.webp'
          }
        }
      }),
      starlightChangelogs(),
    ],
    components: {
      SocialIcons: './src/components/custom-social-icons.astro', // to remove the default RSS icon
      Header: './src/components/custom-header.astro', // marketing navbar on pages with marketingNav: true
      Footer: './src/components/custom-footer.astro',
      PageTitle: './src/components/custom-page-title.astro',  // Removes Page title from splash screens
      Head: './src/components/custom-head.astro', // per-page OG images for marketing pages
    },
    sidebar: [
      { label: 'Getting Started', items: [{ autogenerate: { directory: 'getting-started' } }] },
      {
        label: 'User Settings',
        items: [
          'account/overview',
          'account/change-password',
          'account/security',
          'account/apps',
          'account/general',
          'account/applications',
          'account/invite',
          'account/analytics',
          'account/leaderboard',
          'account/subscription',
          'account/claims',
        ],
      },
      {
        label: 'Portal',
        items: [
          'portal/overview',
          'portal/create-account',
          'portal/dashboard',
          'portal/tasks',
          'portal/notifications',
          { label: 'Extranet', collapsed: true, items: [{ autogenerate: { directory: 'portal/extranet' } }] },
          { label: 'Link Manager', collapsed: true, items: [{ autogenerate: { directory: 'portal/link-manager' } }] },
          { label: 'Payment', collapsed: true, items: [{ autogenerate: { directory: 'portal/payment' } }] },
          { label: 'Settings', collapsed: true, items: [{ autogenerate: { directory: 'portal/settings' } }] },
          { label: 'Social', collapsed: true, items: [{ autogenerate: { directory: 'portal/social' } }] },
          { label: 'Studio', collapsed: true, items: [{ autogenerate: { directory: 'portal/studio' } }] },
          { label: 'Travel Agent', collapsed: true, items: [{ autogenerate: { directory: 'portal/travel-agent' } }] },
        ],
      },
      { label: 'Booking Engine', items: [{ autogenerate: { directory: 'booking-engine' } }] },
      {
        label: 'Guides',
        items: [
          { label: 'For Affiliates', collapsed: true, items: [{ autogenerate: { directory: 'guides/affiliates' } }] },
          { label: 'For Hoteliers', collapsed: true, items: [{ autogenerate: { directory: 'guides/hoteliers' } }] },
          { label: 'For Integrators', collapsed: true, items: [{ autogenerate: { directory: 'guides/integrators' } }] },
          { label: 'General', collapsed: true, items: [{ autogenerate: { directory: 'guides/general' } }] },
        ],
      },
      { label: 'Webinars', items: [{ autogenerate: { directory: 'webinars' } }] },
      { label: 'Integrations', collapsed: true, items: [{ autogenerate: { directory: 'integrations' } }] },
      { label: 'Developers', items: [{ autogenerate: { directory: 'developers' } }] },
      {
        label: 'API', collapsed: true, items: [
          { label: 'Overview', link: '/api/overview' },
          apiSidebarGroup,
        ],
      },
    {
      label: 'Releases',
      items: [
        { label: 'Overview', link: '/changelog/overview/' },
        {
          label: 'Application',
          collapsed: true,
          items: [...makeChangelogsSidebarLinks([
            {
              type: 'recent',
              base: 'changelog/application',
              count: 5
            },
          ])],
        },
        {
          label: 'Platform',
          collapsed: true,
          items: [...makeChangelogsSidebarLinks([
            {
              type: 'recent',
              base: 'changelog/platform',
              count: 5
            },
          ])],
        },
      ]
    },
    ],
    locales: {
      root: {
        label: 'English',
        lang: 'en', // lang is required for root locales
      },
      'id': { label: 'Bahasa Indonesia', lang: 'id' },
      'ms': { label: 'Bahasa Malaysia', lang: 'ms' },
      'bg': { label: 'Български', lang: 'bg' },
      'ca': { label: 'Català', lang: 'ca' },
      'cs': { label: 'Čeština', lang: 'cs' },
      'da': { label: 'Dansk', lang: 'da' },
      'de': { label: 'Deutsch', lang: 'de' },
      'et': { label: 'Eesti', lang: 'et' },
      'es': { label: 'Español', lang: 'es' },
      'es-AR': { label: 'Español (AR)', lang: 'es-AR' },
      'es-MX': { label: 'Español (MX)', lang: 'es-MX' },
      'tl': { label: 'Filipino', lang: 'tl' },
      'fi': { label: 'Suomi', lang: 'fi' },
      'fr': { label: 'Français', lang: 'fr' },
      'el': { label: 'Ελληνικά', lang: 'el' },
      'he': { label: 'עברית', lang: 'he' },
      'hi': { label: 'हिन्दी', lang: 'hi' },
      'hr': { label: 'Hrvatski', lang: 'hr' },
      'hu': { label: 'Magyar', lang: 'hu' },
      'is': { label: 'Íslenska', lang: 'is' },
      'it': { label: 'Italiano', lang: 'it' },
      'ja': { label: '日本語', lang: 'ja' },
      'ko': { label: '한국어', lang: 'ko' },
      'lv': { label: 'Latviski', lang: 'lv' },
      'lt': { label: 'Lietuvių', lang: 'lt' },
      'nl': { label: 'Nederlands', lang: 'nl' },
      'no': { label: 'Norsk', lang: 'no' },
      'pl': { label: 'Polski', lang: 'pl' },
      'pt-BR': { label: 'Português (BR)', lang: 'pt-BR' },
      'pt-PT': { label: 'Português (PT)', lang: 'pt-PT' },
      'ro': { label: 'Română', lang: 'ro' },
      'ru': { label: 'Русский', lang: 'ru' },
      'sk': { label: 'Slovenčina', lang: 'sk' },
      'sl': { label: 'Slovenščina', lang: 'sl' },
      'sr': { label: 'Srpski', lang: 'sr' },
      'sv': { label: 'Svenska', lang: 'sv' },
      'th': { label: 'ภาษาไทย', lang: 'th' },
      'tr': { label: 'Türkçe', lang: 'tr' },
      'uk': { label: 'Українська', lang: 'uk' },
      'vi': { label: 'Tiếng Việt', lang: 'vi' },
      'ar': { label: 'العربية', lang: 'ar' },
      'zh-CN': { label: '简体中文', lang: 'zh-CN' },
      'zh-TW': { label: '繁體中文', lang: 'zh-TW' },
    },
  }), sitemap(), icon(), markdoc()],
  vite: {
    plugins: [tailwindcss()]
  }
});
