/*
 * Copyright (c) wink.travel 2026
 */
// Reads the per-audience OpenAPI documents from monorepo-java's BUILD OUTPUT and writes them to
// ./schemas/<group>.json for use by starlight-openapi at build time.
//
// One document per audience (rather than the single aggregate), so the sidebar is organised by
// audience instead of being one flat 80+ tag dump. The ids here must stay in sync with
// INVENTORY_GROUPS / INTEGRATIONS_GROUPS / PARTNER_GROUPS in astro.config.mjs.
//
// NOTHING IS FETCHED, and that is the point.
//
// These documents used to be pulled from a running deployment's /v3/api-docs/<group>. That has two
// failure modes and we hit both. It documents the last DEPLOY rather than the code, silently -- production
// served the Partner spec with 2 paths and 6 schemas for months while the code had 13 and 57. And the
// snapshot carries whatever environment it was taken against: every schema except partner spent months
// telling integrators to authenticate at https://dev-iam.wink.travel:9000/oauth2/token and call hosts
// unreachable from outside the network, because someone synced against dev and committed it.
//
// A build artifact cannot be pointed at the wrong environment. It is generated from the code with
// production values and is environment-independent by construction, so there is no --env flag here and no
// host to get wrong. If you find yourself adding a fetch back, read the two paragraphs above first.
//
// Generate the inputs in the monorepo checkout before running this:
//
//   mvnd test    -pl apps/inventory-app,apps/integrations-app   # surefire writes target/openapi/*.json
//   mvnd package -pl open-api/open-api-grpc -DskipTests         # exec:java writes partner.json
//
// A missing input FAILS the run rather than quietly keeping the previous snapshot, which is how a site
// ends up publishing a months-old contract without saying so.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

import { loadEnv } from "./load-env.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMAS_DIR = resolve(__dirname, "..", "schemas");

// Must run before the WINK_* reads below.
loadEnv();

// springdoc audience group ids per API. Keep in sync with astro.config.mjs.
// One document per audience -> sidebar is Audience › Resource(tag) › Operation.
// Served by inventory-app. Generated by InventoryOpenApiSpecWriterTest (surefire), same mechanism as
// channel-manager below: a Spring MVC surface has no protobuf descriptor, so springdoc reads the
// annotations from a hand-assembled web context with no application running.
const INVENTORY_GROUPS: readonly string[] = [
  "reference", "extranet", "booking-engine", "studio", "social", "link-manager", "settings", "payment", "user", "travel-agent",
];

// Served by integrations-app: the channel-manager / vendor-integration API
// (/api/channel-manager/**, entity-scoped config, Google Hotel).
//
// The backend group was renamed "partner" -> "channel-manager" (IntegrationsOpenApiConfig
// #channelManagerApi) so the group id matches the paths it documents and no longer collides with
// partner-app's Partner Integrator API. The group/audience remapping this pair used to perform now
// happens at the source, so both sides are identical -- keep the shape anyway, because it is what
// makes a future divergence a one-line change instead of a refactor.
const INTEGRATIONS_GROUPS: readonly { readonly group: string; readonly audience: string }[] = [
  { group: "channel-manager", audience: "channel-manager" },
];

// Served by the standalone partner-app, not integrations-app. Renamed from
// "integrator" to "partner" backend-side (PartnerGrpcOpenApiConfig#GRPC_GROUP) once
// "partner" was freed up above.
//
// NOTE: this document now describes partner-app's gRPC surface, generated from the protobuf
// descriptors -- not the REST controllers under /api/partner/**, whose springdoc group was removed.
// The REST endpoints are still served; they are simply no longer documented, because gRPC is the
// transport integrators should build against and the REST controllers go away at cutover. Expect
// the refreshed snapshot to be far smaller and to contain gRPC-style paths
// (/wink.grpc.v1.Service/Method).
const PARTNER_GROUPS: readonly { readonly group: string; readonly audience: string }[] = [
  { group: "partner", audience: "partner" },
];

// Every schema is a BUILD artifact of the code it describes, so no deployment is involved for any of
// them. The `kind` discriminator is kept -- rather than inlining the path -- because it is the seam where
// a fetch would have to be reintroduced, and that should be a visible, deliberate edit rather than a
// one-word change to a string.
//
// partner-app is why this became non-negotiable rather than merely preferable: it is gRPC-only, and Cloud
// Run exposes one port, so once Netty takes it there is no servlet left to serve /v3/api-docs at all.
type SchemaSource = { readonly kind: "file"; readonly path: string };

type SchemaTarget = {
  readonly name: string;
  readonly source: SchemaSource;
  readonly outFile: string;
};

const optionalEnvPath = (name: string, fallback: string): string => {
  const value = process.env[name];
  return value && value.trim().length > 0 ? value : fallback;
};

// Where monorepo-java is checked out, for the file-sourced schemas below. Override with
// WINK_MONOREPO_PATH when the two repos are not siblings; an absolute value wins, as resolve() gives
// an absolute segment precedence.
const MONOREPO_PATH = resolve(
  __dirname, "..", optionalEnvPath("WINK_MONOREPO_PATH", "../monorepo-java")
);

// The generated Partner document. NOT committed -- it is build output under target/, and monorepo-java
// gitignores that. Run this first, in the monorepo checkout:
//
//   mvnd package -pl open-api/open-api-grpc -DskipTests
//
// The file that IS committed there is the golden TEST fixture, built with placeholder values on
// purpose; publishing it would put "0.0.0-TEST" on the version badge, which persist() refuses to do.
const PARTNER_SCHEMA_FILE = resolve(
  MONOREPO_PATH, "open-api/open-api-grpc/target/openapi/partner.json"
);

// integrations-app's channel-manager document, generated the same way but by a different mechanism: a
// Spring MVC surface has no descriptor, so springdoc reads the annotations from a hand-assembled web
// context in IntegrationsOpenApiSpecWriterTest. Produced by SUREFIRE, so a `-DskipTests` build does not
// create it -- see the OpenAPI schema artifacts section in monorepo-java's CLAUDE.md.
const INTEGRATIONS_SCHEMA_DIR = resolve(MONOREPO_PATH, "apps/integrations-app/target/openapi");

// inventory-app's ten audience documents, generated the same way and by the same mechanism. Also produced
// by SUREFIRE, so a `-DskipTests` build does not create them.
const INVENTORY_SCHEMA_DIR = resolve(MONOREPO_PATH, "apps/inventory-app/target/openapi");

const targets: readonly SchemaTarget[] = [
  ...INVENTORY_GROUPS.map((group) => ({
    name: group,
    source: {
      kind: "file" as const,
      path: resolve(INVENTORY_SCHEMA_DIR, `${group}.json`),
    },
    outFile: `${group}.json`,
  })),
  ...INTEGRATIONS_GROUPS.map(({ group, audience }) => ({
    name: audience,
    source: {
      kind: "file" as const,
      path: resolve(INTEGRATIONS_SCHEMA_DIR, `${group}.json`),
    },
    outFile: `${audience}.json`,
  })),
  // Works for any commit without deploying it, but it does require that commit to have been BUILT: the
  // file lives under target/ and is not committed.
  ...PARTNER_GROUPS.map(({ audience }) => ({
    name: audience,
    source: { kind: "file" as const, path: PARTNER_SCHEMA_FILE },
    outFile: `${audience}.json`,
  })),
];

const ensureDir = (dir: string): void => {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
};

const isOpenApiDoc = (value: unknown): boolean => {
  if (typeof value !== "object" || value === null) return false;
  const obj = value as Record<string, unknown>;
  return typeof obj.openapi === "string" || typeof obj.swagger === "string";
};

// Distinguishes "upstream is having a moment" from "our config is wrong". Both keep the existing
// snapshot, but only the second is a bug we must not ship past.
type SyncResult = "refreshed" | "stale" | "unknown-group";

/**
 * The version PartnerOpenApiDocumentTest builds its golden fixture with. Matched exactly rather than by
 * substring: a real version is a semver from ${revision}, and a loose `includes("TEST")` would reject a
 * legitimate one that happened to contain it.
 */
const GOLDEN_FIXTURE_VERSION = "0.0.0-TEST";

/** Validates and writes one document read off disk. */
const persist = (target: SchemaTarget, outPath: string, body: string): SyncResult => {
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    console.warn(`  ✗ Not valid JSON — keeping existing snapshot`);
    return "stale";
  }
  if (!isOpenApiDoc(parsed)) {
    console.warn(`  ✗ Does not look like an OpenAPI/Swagger doc — keeping existing snapshot`);
    return "stale";
  }
  // Every generator defaults to a placeholder version so a version bump does not churn its golden file.
  // Publishing one would put "0.0.0-TEST" on the docs site's version badge, so refuse it. There are two
  // ways to arrive here and they have different fixes, so name both rather than guess.
  const info = (parsed as Record<string, unknown>).info as Record<string, unknown> | undefined;
  if (typeof info?.version === "string" && info.version === GOLDEN_FIXTURE_VERSION) {
    console.error(
      `  ✗ info.version is "${info.version}" — the placeholder, not a published build.\n` +
      `    The springdoc generators (inventory, integrations) stamp the real revision only when asked:\n` +
      `      mvnd test -pl apps/inventory-app     -Dinventory.openapi.version=<revision>\n` +
      `      mvnd test -pl apps/integrations-app  -Dintegrations.openapi.version=<revision>\n` +
      `    partner bakes it in automatically, so for that one check you are reading\n` +
      `    target/openapi/partner.json and not src/test/resources. Keeping ${outPath}.`
    );
    return "unknown-group";
  }
  const pretty = JSON.stringify(parsed, null, 2) + "\n";
  writeFileSync(outPath, pretty, "utf8");
  const paths = (parsed as Record<string, unknown>).paths as Record<string, unknown> | undefined;
  console.log(`  ✓ wrote ${target.outFile} (${paths ? Object.keys(paths).length : 0} path(s))`);
  return "refreshed";
};

/**
 * Reads a build-generated schema off disk.
 *
 * A missing file is treated like a 404, not like a network blip: it means the generator moved, was
 * renamed, or was never run for this checkout. That is config drift, never transient, and quietly keeping
 * the previous snapshot is how the site publishes a stale contract without saying so.
 */
const syncFromFile = (target: SchemaTarget, path: string, outPath: string): SyncResult => {
  process.stdout.write(`→ ${target.name}: READ ${path}\n`);
  if (!existsSync(path)) {
    console.error(
      `  ✗ No such file. This schema is generated by monorepo-java, not served by an app.\n` +
      `    Generate it with, in the monorepo checkout:\n` +
      `      mvnd test    -pl apps/inventory-app,apps/integrations-app\n` +
      `      mvnd package -pl open-api/open-api-grpc -DskipTests\n` +
      `    or point WINK_MONOREPO_PATH at your checkout. Keeping ${outPath}, but this run will fail.`
    );
    return "unknown-group";
  }
  try {
    return persist(target, outPath, readFileSync(path, "utf8"));
  } catch (err) {
    console.warn(`  ✗ ${err instanceof Error ? err.message : String(err)} — keeping existing snapshot`);
    return "stale";
  }
};

const syncOne = (target: SchemaTarget): SyncResult => {
  const outPath = resolve(SCHEMAS_DIR, target.outFile);
  return syncFromFile(target, target.source.path, outPath);
};

const main = (): void => {
  // Directories, not hosts. There is no environment to print: every document below is generated from
  // the code with production values baked in, which is the property that makes the published reference
  // impossible to point at a dev deployment.
  console.log(
    `Reading schemas from monorepo-java build output\n` +
    `  inventory    = ${INVENTORY_SCHEMA_DIR}\n` +
    `  integrations = ${INTEGRATIONS_SCHEMA_DIR}\n` +
    `  partner      = ${PARTNER_SCHEMA_FILE}\n`
  );

  ensureDir(SCHEMAS_DIR);
  // Sequential to keep the log readable.
  const results: SyncResult[] = targets.map(syncOne);
  const okCount = results.filter((r) => r === "refreshed").length;
  const unknownGroups = results.filter((r) => r === "unknown-group").length;
  console.log(`\nDone: ${okCount}/${targets.length} schemas refreshed.`);
  if (okCount < targets.length) {
    console.log(
      "Note: a failed read does not overwrite the existing snapshot. Build the monorepo and re-run."
    );
  }
  if (unknownGroups > 0) {
    // Exit non-zero so a group rename cannot slip through a green run. Transient failures still
    // exit 0 — the point is to fail on config drift, not on a backend restarting.
    console.error(
      `\n✗ ${unknownGroups} group id(s) no longer exist upstream. Fix the ids in this file before ` +
      `publishing; the site would otherwise build against stale snapshots without saying so.`
    );
    process.exit(1);
  }
};

try {
  main();
} catch (err) {
  console.error(err);
  process.exit(1);
}
